/** Traducciones de interfaz para el escaparate internacional; las fichas se traducen en el servidor al publicarlas. */
export const locales = [
  { code: "es", label: "Español" }, { code: "en", label: "English" }, { code: "nl", label: "Nederlands" }, { code: "de", label: "Deutsch" },
  { code: "sv", label: "Svenska" }, { code: "no", label: "Norsk" }, { code: "fr", label: "Français" }, { code: "ro", label: "Română" },
  { code: "ru", label: "Русский" }, { code: "zh-CN", label: "中文" }, { code: "de-CH", label: "Deutsch (CH)" }, { code: "fr-CH", label: "Français (CH)" }, { code: "it-CH", label: "Italiano (CH)" },
] as const;
export type Locale = (typeof locales)[number]["code"];

type Copy = { homes: string; method: string; build: string; contact: string; admin: string; international: string; title: string; description: string; explore: string; how: string; search: string; portfolio: string; propertyAction: string; details: string; help: string; constructionKicker: string; constructionTitle: string; constructionText: string; constructionCta: string; name: string; email: string; phone: string; location: string; province: string; budget: string; message: string; send: string; constructionSent: string; privacy: string; allAreas: string; allTypes: string; allBudget: string; loading: string; empty: string; emptyText: string; language: string; direct: string; visit: string; }; 

const es: Copy = { homes: "Viviendas", method: "Nuestro método", build: "Construye tu casa", contact: "Contacto", admin: "Administrar", international: "Selección internacional", title: "Encuentra un lugar que se parezca a ti.", description: "Viviendas seleccionadas por Vivienda Nova, con información y atención personalizada.", explore: "Explorar viviendas", how: "Cómo funciona", search: "Buscar viviendas", portfolio: "En cartera ahora", propertyAction: "Solicitar información", details: "Ver detalles", help: "¿Necesitas ayuda?", constructionKicker: "Construcción a medida", constructionTitle: "Tu casa, desde cero.", constructionText: "Cuéntanos dónde quieres construir y qué necesitas. Estudiaremos tu proyecto y te pondremos en contacto con el equipo adecuado.", constructionCta: "Cuéntanos tu proyecto", name: "Tu nombre", email: "Tu correo", phone: "Tu teléfono", location: "Lugar donde quieres construir", province: "Provincia", budget: "Presupuesto orientativo", message: "Cuéntanos tu idea", send: "Enviar proyecto", constructionSent: "Hemos recibido tu proyecto. Te contactaremos pronto.", privacy: "Al enviar aceptas el tratamiento de tus datos para responder a tu solicitud.", allAreas: "Todas las zonas", allTypes: "Todos los tipos", allBudget: "Sin límite", loading: "Preparando la selección.", empty: "La próxima vivienda puede empezar aquí.", emptyText: "Actualizamos la cartera con una selección breve y deliberada.", language: "Idioma", direct: "Atención Vivienda Nova", visit: "Solicitar información" };
const translations: Record<Locale, Copy> = {
  es,
  en: { ...es, homes: "Homes", method: "How it works", build: "Build your home", contact: "Contact", admin: "Manage", international: "International selection", title: "Find a place that feels like you.", description: "Homes selected by Vivienda Nova, with information and personal support.", explore: "Explore homes", how: "How it works", search: "Search homes", portfolio: "Available now", propertyAction: "Request information", details: "View details", help: "Need help?", constructionKicker: "Custom build", constructionTitle: "Your home, from the ground up.", constructionText: "Tell us where you want to build and what you need. We will review your project and connect you with the right team.", constructionCta: "Tell us about your project", name: "Your name", email: "Your email", phone: "Your phone", location: "Where you want to build", province: "Province / region", budget: "Indicative budget", message: "Tell us about your idea", send: "Send project", constructionSent: "We received your project. We will contact you shortly.", privacy: "By sending, you agree to the processing of your data to answer your request.", allAreas: "All areas", allTypes: "All types", allBudget: "No limit", loading: "Preparing the selection.", empty: "The next home may start here.", emptyText: "We update the portfolio with a brief, deliberate selection.", language: "Language", direct: "Vivienda Nova support", visit: "Request information" },
  nl: { ...es, homes: "Woningen", method: "Onze werkwijze", build: "Bouw uw huis", contact: "Contact", admin: "Beheren", international: "Internationale selectie", title: "Vind een plek die bij u past.", description: "Door Vivienda Nova geselecteerde woningen, met persoonlijke informatie en begeleiding.", explore: "Woningen bekijken", how: "Hoe het werkt", search: "Woningen zoeken", portfolio: "Nu beschikbaar", propertyAction: "Informatie aanvragen", details: "Details bekijken", help: "Hulp nodig?", constructionKicker: "Maatwerkbouw", constructionTitle: "Uw huis, vanaf nul.", constructionText: "Vertel ons waar u wilt bouwen en wat u nodig heeft. Wij bekijken uw project en brengen u in contact met het juiste team.", constructionCta: "Vertel over uw project", name: "Uw naam", email: "Uw e-mail", phone: "Uw telefoon", location: "Waar wilt u bouwen", province: "Provincie / regio", budget: "Indicatief budget", message: "Vertel over uw idee", send: "Project versturen", constructionSent: "Wij hebben uw project ontvangen.", privacy: "Door te versturen stemt u in met de verwerking van uw gegevens.", allAreas: "Alle zones", allTypes: "Alle types", allBudget: "Geen limiet", loading: "Selectie voorbereiden.", empty: "De volgende woning kan hier beginnen.", emptyText: "We actualiseren de portefeuille zorgvuldig.", language: "Taal", direct: "Vivienda Nova begeleiding", visit: "Informatie aanvragen" },
  de: { ...es, homes: "Immobilien", method: "Unser Ansatz", build: "Haus bauen", contact: "Kontakt", admin: "Verwaltung", international: "Internationale Auswahl", title: "Finden Sie einen Ort, der zu Ihnen passt.", description: "Von Vivienda Nova ausgewählte Immobilien mit persönlicher Information und Betreuung.", explore: "Immobilien entdecken", how: "So funktioniert es", search: "Immobilien suchen", portfolio: "Aktuell verfügbar", propertyAction: "Information anfordern", details: "Details ansehen", help: "Brauchen Sie Hilfe?", constructionKicker: "Individueller Hausbau", constructionTitle: "Ihr Haus, von Grund auf.", constructionText: "Sagen Sie uns, wo Sie bauen möchten. Wir prüfen Ihr Projekt und verbinden Sie mit dem passenden Team.", constructionCta: "Projekt beschreiben", name: "Ihr Name", email: "Ihre E-Mail", phone: "Ihr Telefon", location: "Wo möchten Sie bauen", province: "Provinz / Region", budget: "Ungefähres Budget", message: "Ihre Idee", send: "Projekt senden", constructionSent: "Wir haben Ihr Projekt erhalten.", privacy: "Mit dem Senden stimmen Sie der Verarbeitung Ihrer Daten zu.", allAreas: "Alle Gebiete", allTypes: "Alle Typen", allBudget: "Kein Limit", loading: "Auswahl wird vorbereitet.", empty: "Das nächste Zuhause könnte hier beginnen.", emptyText: "Wir aktualisieren das Portfolio sorgfältig.", language: "Sprache", direct: "Vivienda Nova Betreuung", visit: "Information anfordern" },
  sv: { ...es, homes: "Bostäder", method: "Så fungerar det", build: "Bygg ditt hem", contact: "Kontakt", admin: "Administrera", international: "Internationellt urval", title: "Hitta en plats som passar dig.", description: "Bostäder utvalda av Vivienda Nova med personlig information och hjälp.", explore: "Utforska bostäder", how: "Så fungerar det", search: "Sök bostäder", portfolio: "Tillgängligt nu", propertyAction: "Begär information", details: "Se detaljer", help: "Behöver du hjälp?", constructionKicker: "Skräddarsytt bygge", constructionTitle: "Ditt hem, från grunden.", constructionText: "Berätta var du vill bygga. Vi går igenom ditt projekt och kopplar dig till rätt team.", constructionCta: "Berätta om ditt projekt", name: "Ditt namn", email: "Din e-post", phone: "Din telefon", location: "Var vill du bygga", province: "Provins / region", budget: "Ungefärlig budget", message: "Berätta om din idé", send: "Skicka projekt", constructionSent: "Vi har fått ditt projekt.", privacy: "Genom att skicka godkänner du behandlingen av dina uppgifter.", allAreas: "Alla områden", allTypes: "Alla typer", allBudget: "Ingen gräns", loading: "Förbereder urvalet.", empty: "Nästa bostad kan börja här.", emptyText: "Vi uppdaterar portföljen omsorgsfullt.", language: "Språk", direct: "Vivienda Nova hjälp", visit: "Begär information" },
  no: { ...es, homes: "Boliger", method: "Slik fungerer det", build: "Bygg ditt hjem", contact: "Kontakt", admin: "Administrer", international: "Internasjonalt utvalg", title: "Finn et sted som passer deg.", description: "Boliger valgt av Vivienda Nova med personlig informasjon og oppfølging.", explore: "Utforsk boliger", how: "Slik fungerer det", search: "Søk boliger", portfolio: "Tilgjengelig nå", propertyAction: "Be om informasjon", details: "Se detaljer", help: "Trenger du hjelp?", constructionKicker: "Skreddersydd bygg", constructionTitle: "Ditt hjem, fra bunnen av.", constructionText: "Fortell oss hvor du vil bygge. Vi vurderer prosjektet og kobler deg til riktig team.", constructionCta: "Fortell om prosjektet", name: "Ditt navn", email: "Din e-post", phone: "Din telefon", location: "Hvor vil du bygge", province: "Fylke / region", budget: "Veiledende budsjett", message: "Fortell om ideen", send: "Send prosjekt", constructionSent: "Vi har mottatt prosjektet ditt.", privacy: "Ved å sende godtar du behandling av opplysningene dine.", allAreas: "Alle områder", allTypes: "Alle typer", allBudget: "Ingen grense", loading: "Forbereder utvalget.", empty: "Neste bolig kan starte her.", emptyText: "Vi oppdaterer porteføljen nøye.", language: "Språk", direct: "Vivienda Nova oppfølging", visit: "Be om informasjon" },
  fr: { ...es, homes: "Biens", method: "Notre méthode", build: "Construire votre maison", contact: "Contact", admin: "Gérer", international: "Sélection internationale", title: "Trouvez un lieu qui vous ressemble.", description: "Des biens sélectionnés par Vivienda Nova, avec information et accompagnement personnalisé.", explore: "Explorer les biens", how: "Comment cela fonctionne", search: "Rechercher un bien", portfolio: "En portefeuille", propertyAction: "Demander des informations", details: "Voir les détails", help: "Besoin d'aide ?", constructionKicker: "Construction sur mesure", constructionTitle: "Votre maison, depuis zéro.", constructionText: "Dites-nous où vous souhaitez construire. Nous étudierons votre projet et vous mettrons en relation avec la bonne équipe.", constructionCta: "Parlez-nous du projet", name: "Votre nom", email: "Votre e-mail", phone: "Votre téléphone", location: "Où souhaitez-vous construire", province: "Province / région", budget: "Budget indicatif", message: "Votre idée", send: "Envoyer le projet", constructionSent: "Nous avons reçu votre projet.", privacy: "En envoyant, vous acceptez le traitement de vos données.", allAreas: "Toutes les zones", allTypes: "Tous les types", allBudget: "Sans limite", loading: "Préparation de la sélection.", empty: "Le prochain bien peut commencer ici.", emptyText: "Nous actualisons le portefeuille avec soin.", language: "Langue", direct: "Accompagnement Vivienda Nova", visit: "Demander des informations" },
  ro: { ...es, homes: "Locuințe", method: "Cum funcționează", build: "Construiește-ți casa", contact: "Contact", admin: "Administrare", international: "Selecție internațională", title: "Găsește un loc care ți se potrivește.", description: "Proprietăți selectate de Vivienda Nova, cu informații și sprijin personalizat.", explore: "Explorează locuințe", how: "Cum funcționează", search: "Caută locuințe", portfolio: "Disponibile acum", propertyAction: "Solicită informații", details: "Vezi detalii", help: "Ai nevoie de ajutor?", constructionKicker: "Construcție personalizată", constructionTitle: "Casa ta, de la zero.", constructionText: "Spune-ne unde vrei să construiești. Îți analizăm proiectul și te conectăm cu echipa potrivită.", constructionCta: "Spune-ne despre proiect", name: "Numele tău", email: "E-mailul tău", phone: "Telefonul tău", location: "Unde vrei să construiești", province: "Județ / regiune", budget: "Buget orientativ", message: "Spune-ne ideea ta", send: "Trimite proiectul", constructionSent: "Am primit proiectul tău.", privacy: "Prin trimitere, accepți prelucrarea datelor tale.", allAreas: "Toate zonele", allTypes: "Toate tipurile", allBudget: "Fără limită", loading: "Pregătim selecția.", empty: "Următoarea locuință poate începe aici.", emptyText: "Actualizăm portofoliul cu grijă.", language: "Limbă", direct: "Asistență Vivienda Nova", visit: "Solicită informații" },
  ru: { ...es, homes: "Объекты", method: "Как это работает", build: "Построить дом", contact: "Контакты", admin: "Управление", international: "Международная подборка", title: "Найдите место, которое вам подходит.", description: "Объекты, отобранные Vivienda Nova, с персональной информацией и поддержкой.", explore: "Смотреть объекты", how: "Как это работает", search: "Поиск объектов", portfolio: "Доступно сейчас", propertyAction: "Запросить информацию", details: "Подробнее", help: "Нужна помощь?", constructionKicker: "Индивидуальное строительство", constructionTitle: "Ваш дом с нуля.", constructionText: "Расскажите, где вы хотите строить. Мы изучим проект и свяжем вас с нужной командой.", constructionCta: "Рассказать о проекте", name: "Ваше имя", email: "Ваш e-mail", phone: "Ваш телефон", location: "Где вы хотите строить", province: "Регион", budget: "Ориентировочный бюджет", message: "Расскажите о вашей идее", send: "Отправить проект", constructionSent: "Мы получили ваш проект.", privacy: "Отправляя форму, вы соглашаетесь на обработку данных.", allAreas: "Все районы", allTypes: "Все типы", allBudget: "Без ограничений", loading: "Готовим подборку.", empty: "Следующий дом может начаться здесь.", emptyText: "Мы тщательно обновляем портфель.", language: "Язык", direct: "Поддержка Vivienda Nova", visit: "Запросить информацию" },
  "zh-CN": { ...es, homes: "房源", method: "服务方式", build: "建造您的家", contact: "联系", admin: "管理", international: "国际精选", title: "找到真正适合您的家。", description: "由 Vivienda Nova 精选的房源，提供个性化信息与服务。", explore: "浏览房源", how: "了解流程", search: "搜索房源", portfolio: "当前房源", propertyAction: "请求信息", details: "查看详情", help: "需要帮助？", constructionKicker: "定制建房", constructionTitle: "从零开始打造您的家。", constructionText: "告诉我们您想在哪里建造以及您的需求。我们将评估项目并为您联系合适的团队。", constructionCta: "告诉我们您的项目", name: "您的姓名", email: "您的邮箱", phone: "您的电话", location: "您希望建造的地点", province: "省 / 地区", budget: "预算范围", message: "告诉我们您的想法", send: "提交项目", constructionSent: "我们已收到您的项目。", privacy: "提交即表示您同意处理您的数据以回复您的请求。", allAreas: "所有地区", allTypes: "所有类型", allBudget: "不限", loading: "正在准备精选房源。", empty: "下一个房源可能从这里开始。", emptyText: "我们谨慎更新房源组合。", language: "语言", direct: "Vivienda Nova 服务", visit: "请求信息" },
  "de-CH": es,
  "fr-CH": es,
  "it-CH": { ...es, homes: "Immobili", method: "Come funziona", build: "Costruisci la tua casa", contact: "Contatto", admin: "Gestisci", international: "Selezione internazionale", title: "Trova un luogo che ti somigli.", description: "Immobili selezionati da Vivienda Nova, con informazioni e assistenza personalizzata.", explore: "Esplora immobili", how: "Come funziona", search: "Cerca immobili", portfolio: "Disponibili ora", propertyAction: "Richiedi informazioni", details: "Vedi dettagli", help: "Hai bisogno di aiuto?", constructionKicker: "Costruzione su misura", constructionTitle: "La tua casa, da zero.", constructionText: "Dicci dove vuoi costruire e cosa ti serve. Esamineremo il progetto e ti metteremo in contatto con il team giusto.", constructionCta: "Racconta il progetto", name: "Il tuo nome", email: "La tua e-mail", phone: "Il tuo telefono", location: "Dove vuoi costruire", province: "Provincia / regione", budget: "Budget indicativo", message: "Racconta la tua idea", send: "Invia progetto", constructionSent: "Abbiamo ricevuto il tuo progetto.", privacy: "Inviando accetti il trattamento dei tuoi dati.", allAreas: "Tutte le zone", allTypes: "Tutti i tipi", allBudget: "Nessun limite", loading: "Prepariamo la selezione.", empty: "La prossima casa può iniziare qui.", emptyText: "Aggiorniamo il portafoglio con cura.", language: "Lingua", direct: "Assistenza Vivienda Nova", visit: "Richiedi informazioni" },
};
translations["de-CH"] = { ...translations.de };
translations["fr-CH"] = { ...translations.fr };
export function getCopy(locale: Locale): Copy { return translations[locale] || es; }
export function detectLocale(enabled: string[]): Locale { const fallback: Locale = "es"; if (typeof navigator === "undefined") return fallback; for (const language of navigator.languages) { const exact = locales.find((item) => item.code.toLowerCase() === language.toLowerCase())?.code; if (exact && enabled.includes(exact)) return exact; const base = language.toLowerCase().split("-")[0]; const match = locales.find((item) => item.code === base)?.code; if (match && enabled.includes(match)) return match; } return fallback; }


type SearchLabels = { country: string; allCountries: string; allProvinces: string; municipality: string; allMunicipalities: string; neighborhood: string; textReferenceAddress: string; anyBedrooms: string; bedroomsOrMore: (count: number) => string };
const searchLabels: Record<Locale, SearchLabels> = {
  es: { country: "País", allCountries: "Todos los países", allProvinces: "Todas las provincias", municipality: "Municipio / ciudad", allMunicipalities: "Todos los municipios", neighborhood: "Barrio / zona", textReferenceAddress: "Texto, referencia o dirección", anyBedrooms: "Cualquiera", bedroomsOrMore: (count) => `${count} o más` },
  en: { country: "Country", allCountries: "All countries", allProvinces: "All provinces", municipality: "Town / city", allMunicipalities: "All towns", neighborhood: "Neighbourhood / area", textReferenceAddress: "Text, reference or address", anyBedrooms: "Any", bedroomsOrMore: (count) => `${count} or more` },
  nl: { country: "Land", allCountries: "Alle landen", allProvinces: "Alle provincies", municipality: "Gemeente / stad", allMunicipalities: "Alle gemeenten", neighborhood: "Wijk / gebied", textReferenceAddress: "Tekst, referentie of adres", anyBedrooms: "Alle", bedroomsOrMore: (count) => `${count} of meer` },
  de: { country: "Land", allCountries: "Alle Länder", allProvinces: "Alle Provinzen", municipality: "Gemeinde / Stadt", allMunicipalities: "Alle Gemeinden", neighborhood: "Viertel / Gebiet", textReferenceAddress: "Text, Referenz oder Adresse", anyBedrooms: "Beliebig", bedroomsOrMore: (count) => `${count} oder mehr` },
  sv: { country: "Land", allCountries: "Alla länder", allProvinces: "Alla provinser", municipality: "Kommun / stad", allMunicipalities: "Alla kommuner", neighborhood: "Område", textReferenceAddress: "Text, referens eller adress", anyBedrooms: "Valfritt", bedroomsOrMore: (count) => `${count} eller fler` },
  no: { country: "Land", allCountries: "Alle land", allProvinces: "Alle fylker", municipality: "Kommune / by", allMunicipalities: "Alle kommuner", neighborhood: "Nabolag / område", textReferenceAddress: "Tekst, referanse eller adresse", anyBedrooms: "Valgfritt", bedroomsOrMore: (count) => `${count} eller flere` },
  fr: { country: "Pays", allCountries: "Tous les pays", allProvinces: "Toutes les provinces", municipality: "Commune / ville", allMunicipalities: "Toutes les communes", neighborhood: "Quartier / zone", textReferenceAddress: "Texte, référence ou adresse", anyBedrooms: "Tous", bedroomsOrMore: (count) => `${count} ou plus` },
  ro: { country: "Țară", allCountries: "Toate țările", allProvinces: "Toate provinciile", municipality: "Municipiu / oraș", allMunicipalities: "Toate localitățile", neighborhood: "Cartier / zonă", textReferenceAddress: "Text, referință sau adresă", anyBedrooms: "Oricare", bedroomsOrMore: (count) => `${count} sau mai multe` },
  ru: { country: "Страна", allCountries: "Все страны", allProvinces: "Все регионы", municipality: "Город / населённый пункт", allMunicipalities: "Все города", neighborhood: "Район / зона", textReferenceAddress: "Текст, код или адрес", anyBedrooms: "Любое", bedroomsOrMore: (count) => `${count} или больше` },
  "zh-CN": { country: "国家", allCountries: "所有国家", allProvinces: "所有省份", municipality: "市 / 城镇", allMunicipalities: "所有城市", neighborhood: "街区 / 区域", textReferenceAddress: "关键词、编号或地址", anyBedrooms: "不限", bedroomsOrMore: (count) => `${count}间或以上` },
  "de-CH": {} as SearchLabels,
  "fr-CH": {} as SearchLabels,
  "it-CH": { country: "Paese", allCountries: "Tutti i paesi", allProvinces: "Tutte le province", municipality: "Comune / città", allMunicipalities: "Tutti i comuni", neighborhood: "Quartiere / zona", textReferenceAddress: "Testo, riferimento o indirizzo", anyBedrooms: "Qualsiasi", bedroomsOrMore: (count) => `${count} o più` },
};
searchLabels["de-CH"] = searchLabels.de;
searchLabels["fr-CH"] = searchLabels.fr;
export function getSearchLabels(locale: Locale): SearchLabels { return searchLabels[locale] || searchLabels.es; }
