import { FormEvent, SyntheticEvent, useEffect, useMemo, useState } from "react";
import { Link, useRoute } from "wouter";
import { ArrowLeft, Bath, BedDouble, CalendarDays, Check, ChevronDown, House, MapPin, Ruler, Send } from "lucide-react";
import { trpc } from "@/lib/trpc";
import { detectLocale, locales, type Locale } from "@/lib/i18n";
import PropertyCarousel, { type CardStyle, type CarouselProperty } from "@/components/PropertyCarousel";
import "./PropertyDetail.css";

const fallback = "/manus-storage/chalet-minimalista-piscina_3bd4eca8.jpg";

type Property = CarouselProperty & { address?: string | null; province?: string | null; country?: string | null; priceValue: number; description: string; galleryUrls?: string | null; features?: string | null; latitude?: string | null; longitude?: string | null; tag: string; externalUrl?: string | null; linkMode?: "capture" | "redirect" | "both"; descriptionMode?: "auto" | "compact" | "scroll" | "full"; descriptionHeight?: number; featured?: number };
type Settings = { enabledLocales: string; reservationButtonText?: string | null; reservationButtonBackground?: string | null; reservationButtonColor?: string | null; relatedPropertiesCount?: number; cardStyle?: CardStyle };
type Section = { id: number; title: string; subtitle: string; propertyIds: string; cardStyle: CardStyle; background: string; active: number };

const labels: Record<Locale, { back: string; description: string; about: string; features: string; map: string; showMap: string; hideMap: string; location: string; reserve: string; availability: string; request: string; reservationText: string; name: string; email: string; phone: string; date: string; guests: string; message: string; consent: string; consentReservation: string; send: string; sent: string; error: string; related: string; autoRelated: string; bedrooms: string; bathrooms: string }> = {
  es: { back: "Volver a viviendas", description: "Descripción", about: "Sobre esta vivienda", features: "Características verificadas", map: "Mapa y ubicación", showMap: "Mostrar mapa", hideMap: "Ocultar mapa", location: "Ubicación aproximada", reserve: "Solicitar reserva", availability: "Disponibilidad", request: "Solicita tu reserva", reservationText: "Envíanos tus datos y fecha preferida. Esta solicitud no realiza ningún cobro.", name: "Nombre completo", email: "Correo electrónico", phone: "Teléfono", date: "Fecha preferida", guests: "Personas", message: "Mensaje", consent: "He leído la política de privacidad.", consentReservation: "Autorizo que Vivienda Nova me contacte para gestionar esta solicitud.", send: "Enviar solicitud", sent: "Solicitud recibida. Te contactaremos para confirmar disponibilidad.", error: "Revisa los datos y consentimientos antes de enviar.", related: "También te puede interesar", autoRelated: "Viviendas del mismo tipo, con prioridad para la misma zona.", bedrooms: "dormitorios", bathrooms: "baños" },
  en: { back: "Back to homes", description: "Description", about: "About this home", features: "Verified features", map: "Map and location", showMap: "Show map", hideMap: "Hide map", location: "Approximate location", reserve: "Request reservation", availability: "Availability", request: "Request your reservation", reservationText: "Send your details and preferred date. This request does not take a payment.", name: "Full name", email: "Email address", phone: "Phone", date: "Preferred date", guests: "Guests", message: "Message", consent: "I have read the privacy policy.", consentReservation: "I authorise Vivienda Nova to contact me about this request.", send: "Send request", sent: "Request received. We will contact you to confirm availability.", error: "Check the details and consent boxes before sending.", related: "You may also like", autoRelated: "Homes of the same type, with priority for the same area.", bedrooms: "bedrooms", bathrooms: "bathrooms" },
  nl: { back: "Terug naar woningen", description: "Beschrijving", about: "Over deze woning", features: "Geverifieerde kenmerken", map: "Kaart en locatie", showMap: "Kaart tonen", hideMap: "Kaart verbergen", location: "Geschatte locatie", reserve: "Reservering aanvragen", availability: "Beschikbaarheid", request: "Vraag uw reservering aan", reservationText: "Stuur uw gegevens en voorkeursdatum. Deze aanvraag brengt geen betaling in rekening.", name: "Volledige naam", email: "E-mailadres", phone: "Telefoon", date: "Voorkeursdatum", guests: "Personen", message: "Bericht", consent: "Ik heb het privacybeleid gelezen.", consentReservation: "Ik geef Vivienda Nova toestemming om contact met mij op te nemen.", send: "Aanvraag versturen", sent: "Aanvraag ontvangen. Wij nemen contact op om beschikbaarheid te bevestigen.", error: "Controleer de gegevens en toestemmingen.", related: "Misschien ook interessant", autoRelated: "Woningen van hetzelfde type, met voorrang voor dezelfde buurt.", bedrooms: "slaapkamers", bathrooms: "badkamers" },
  de: { back: "Zurück zu Immobilien", description: "Beschreibung", about: "Über diese Immobilie", features: "Geprüfte Merkmale", map: "Karte und Lage", showMap: "Karte anzeigen", hideMap: "Karte ausblenden", location: "Ungefährer Standort", reserve: "Reservierung anfragen", availability: "Verfügbarkeit", request: "Reservierung anfragen", reservationText: "Senden Sie Ihre Daten und Ihren Wunschtermin. Diese Anfrage löst keine Zahlung aus.", name: "Vollständiger Name", email: "E-Mail", phone: "Telefon", date: "Wunschtermin", guests: "Personen", message: "Nachricht", consent: "Ich habe die Datenschutzrichtlinie gelesen.", consentReservation: "Ich ermächtige Vivienda Nova, mich zu dieser Anfrage zu kontaktieren.", send: "Anfrage senden", sent: "Anfrage erhalten. Wir kontaktieren Sie zur Bestätigung der Verfügbarkeit.", error: "Prüfen Sie die Angaben und Einwilligungen.", related: "Das könnte Sie auch interessieren", autoRelated: "Immobilien desselben Typs, bevorzugt in derselben Gegend.", bedrooms: "Schlafzimmer", bathrooms: "Bäder" },
  sv: { back: "Tillbaka till bostäder", description: "Beskrivning", about: "Om bostaden", features: "Verifierade egenskaper", map: "Karta och plats", showMap: "Visa karta", hideMap: "Dölj karta", location: "Ungefärlig plats", reserve: "Begär reservation", availability: "Tillgänglighet", request: "Begär din reservation", reservationText: "Skicka dina uppgifter och önskat datum. Begäran innebär ingen betalning.", name: "Fullständigt namn", email: "E-postadress", phone: "Telefon", date: "Önskat datum", guests: "Personer", message: "Meddelande", consent: "Jag har läst integritetspolicyn.", consentReservation: "Jag godkänner att Vivienda Nova kontaktar mig om denna begäran.", send: "Skicka begäran", sent: "Begäran mottagen. Vi kontaktar dig för att bekräfta tillgänglighet.", error: "Kontrollera uppgifter och samtycken innan du skickar.", related: "Du kanske också är intresserad av", autoRelated: "Bostäder av samma typ, med prioritet för samma område.", bedrooms: "sovrum", bathrooms: "badrum" },
  no: { back: "Tilbake til boliger", description: "Beskrivelse", about: "Om denne boligen", features: "Verifiserte egenskaper", map: "Kart og beliggenhet", showMap: "Vis kart", hideMap: "Skjul kart", location: "Omtrentlig beliggenhet", reserve: "Be om reservasjon", availability: "Tilgjengelighet", request: "Be om reservasjon", reservationText: "Send opplysningene dine og ønsket dato. Forespørselen medfører ingen betaling.", name: "Fullt navn", email: "E-post", phone: "Telefon", date: "Ønsket dato", guests: "Personer", message: "Melding", consent: "Jeg har lest personvernerklæringen.", consentReservation: "Jeg godkjenner at Vivienda Nova kontakter meg om denne forespørselen.", send: "Send forespørsel", sent: "Forespørselen er mottatt. Vi kontakter deg for å bekrefte tilgjengelighet.", error: "Kontroller opplysninger og samtykker før du sender.", related: "Dette kan også interessere deg", autoRelated: "Boliger av samme type, prioritert i samme område.", bedrooms: "soverom", bathrooms: "bad" },
  fr: { back: "Retour aux logements", description: "Description", about: "À propos de ce bien", features: "Caractéristiques vérifiées", map: "Carte et emplacement", showMap: "Afficher la carte", hideMap: "Masquer la carte", location: "Emplacement approximatif", reserve: "Demander une réservation", availability: "Disponibilité", request: "Demander votre réservation", reservationText: "Envoyez vos coordonnées et la date souhaitée. Cette demande n'entraîne aucun paiement.", name: "Nom complet", email: "Adresse e-mail", phone: "Téléphone", date: "Date souhaitée", guests: "Personnes", message: "Message", consent: "J'ai lu la politique de confidentialité.", consentReservation: "J'autorise Vivienda Nova à me contacter au sujet de cette demande.", send: "Envoyer la demande", sent: "Demande reçue. Nous vous contacterons pour confirmer la disponibilité.", error: "Vérifiez les informations et les consentements avant l'envoi.", related: "Cela pourrait aussi vous intéresser", autoRelated: "Biens du même type, avec priorité à la même zone.", bedrooms: "chambres", bathrooms: "salles de bain" },
  ro: { back: "Înapoi la proprietăți", description: "Descriere", about: "Despre această proprietate", features: "Caracteristici verificate", map: "Hartă și locație", showMap: "Afișează harta", hideMap: "Ascunde harta", location: "Locație aproximativă", reserve: "Solicită rezervare", availability: "Disponibilitate", request: "Solicită rezervarea", reservationText: "Trimiteți datele și data preferată. Cererea nu implică nicio plată.", name: "Nume complet", email: "E-mail", phone: "Telefon", date: "Data preferată", guests: "Persoane", message: "Mesaj", consent: "Am citit politica de confidențialitate.", consentReservation: "Autorizez Vivienda Nova să mă contacteze despre această cerere.", send: "Trimite cererea", sent: "Cerere primită. Vă vom contacta pentru confirmarea disponibilității.", error: "Verificați datele și acordurile înainte de trimitere.", related: "V-ar putea interesa și", autoRelated: "Proprietăți de același tip, cu prioritate pentru aceeași zonă.", bedrooms: "dormitoare", bathrooms: "băi" },
  ru: { back: "Вернуться к объектам", description: "Описание", about: "Об этом объекте", features: "Проверенные характеристики", map: "Карта и расположение", showMap: "Показать карту", hideMap: "Скрыть карту", location: "Примерное расположение", reserve: "Запросить бронирование", availability: "Доступность", request: "Запросить бронирование", reservationText: "Отправьте свои данные и желаемую дату. Этот запрос не является оплатой.", name: "Полное имя", email: "Электронная почта", phone: "Телефон", date: "Желаемая дата", guests: "Количество человек", message: "Сообщение", consent: "Я прочитал(а) политику конфиденциальности.", consentReservation: "Я разрешаю Vivienda Nova связаться со мной по этому запросу.", send: "Отправить запрос", sent: "Запрос получен. Мы свяжемся с вами для подтверждения доступности.", error: "Проверьте данные и согласия перед отправкой.", related: "Вам также может понравиться", autoRelated: "Объекты того же типа, прежде всего в том же районе.", bedrooms: "спальни", bathrooms: "ванные" },
  "zh-CN": { back: "返回房源", description: "房源介绍", about: "关于此房源", features: "已核实的特色", map: "地图与位置", showMap: "显示地图", hideMap: "隐藏地图", location: "大致位置", reserve: "申请预订", availability: "可用性", request: "申请预订", reservationText: "请发送您的信息和首选日期。此申请不会产生任何付款。", name: "姓名", email: "电子邮箱", phone: "电话", date: "首选日期", guests: "人数", message: "留言", consent: "我已阅读隐私政策。", consentReservation: "我同意 Vivienda Nova 就此申请与我联系。", send: "发送申请", sent: "申请已收到。我们将联系您确认可用性。", error: "发送前请检查信息和同意项。", related: "您可能也会感兴趣", autoRelated: "同类型房源，优先展示同一地区的房源。", bedrooms: "卧室", bathrooms: "浴室" },
  "de-CH": { back: "Zurück zu Immobilien", description: "Beschreibung", about: "Über diese Immobilie", features: "Geprüfte Merkmale", map: "Karte und Lage", showMap: "Karte anzeigen", hideMap: "Karte ausblenden", location: "Ungefährer Standort", reserve: "Reservierung anfragen", availability: "Verfügbarkeit", request: "Reservierung anfragen", reservationText: "Senden Sie Ihre Daten und Ihren Wunschtermin. Diese Anfrage löst keine Zahlung aus.", name: "Vollständiger Name", email: "E-Mail", phone: "Telefon", date: "Wunschtermin", guests: "Personen", message: "Nachricht", consent: "Ich habe die Datenschutzrichtlinie gelesen.", consentReservation: "Ich ermächtige Vivienda Nova, mich zu dieser Anfrage zu kontaktieren.", send: "Anfrage senden", sent: "Anfrage erhalten. Wir kontaktieren Sie zur Bestätigung der Verfügbarkeit.", error: "Prüfen Sie die Angaben und Einwilligungen.", related: "Das könnte Sie auch interessieren", autoRelated: "Immobilien desselben Typs, bevorzugt in derselben Gegend.", bedrooms: "Schlafzimmer", bathrooms: "Bäder" },
  "fr-CH": { back: "Retour aux logements", description: "Description", about: "À propos de ce bien", features: "Caractéristiques vérifiées", map: "Carte et emplacement", showMap: "Afficher la carte", hideMap: "Masquer la carte", location: "Emplacement approximatif", reserve: "Demander une réservation", availability: "Disponibilité", request: "Demander votre réservation", reservationText: "Envoyez vos coordonnées et la date souhaitée. Cette demande n'entraîne aucun paiement.", name: "Nom complet", email: "Adresse e-mail", phone: "Téléphone", date: "Date souhaitée", guests: "Personnes", message: "Message", consent: "J'ai lu la politique de confidentialité.", consentReservation: "J'autorise Vivienda Nova à me contacter au sujet de cette demande.", send: "Envoyer la demande", sent: "Demande reçue. Nous vous contacterons pour confirmer la disponibilité.", error: "Vérifiez les informations et les consentements avant l'envoi.", related: "Cela pourrait aussi vous intéresser", autoRelated: "Biens du même type, avec priorité à la même zone.", bedrooms: "chambres", bathrooms: "salles de bain" },
  "it-CH": { back: "Torna agli immobili", description: "Descrizione", about: "Informazioni su questo immobile", features: "Caratteristiche verificate", map: "Mappa e posizione", showMap: "Mostra mappa", hideMap: "Nascondi mappa", location: "Posizione approssimativa", reserve: "Richiedi prenotazione", availability: "Disponibilità", request: "Richiedi la prenotazione", reservationText: "Invia i tuoi dati e la data preferita. Questa richiesta non comporta alcun pagamento.", name: "Nome completo", email: "E-mail", phone: "Telefono", date: "Data preferita", guests: "Persone", message: "Messaggio", consent: "Ho letto l'informativa sulla privacy.", consentReservation: "Autorizzo Vivienda Nova a contattarmi in merito a questa richiesta.", send: "Invia richiesta", sent: "Richiesta ricevuta. Ti contatteremo per confermare la disponibilità.", error: "Controlla i dati e i consensi prima dell'invio.", related: "Potrebbe interessarti anche", autoRelated: "Immobili dello stesso tipo, con priorità per la stessa zona.", bedrooms: "camere", bathrooms: "bagni" },
};

function parseGallery(source?: string | null, fallbackImage?: string) { try { const values = JSON.parse(source || "[]"); return Array.isArray(values) ? values.filter((item): item is string => typeof item === "string" && Boolean(item.trim())).slice(0, 30) : fallbackImage ? [fallbackImage] : []; } catch { return fallbackImage ? [fallbackImage] : []; } }
function parseFeatures(source?: string | null) { try { const values = JSON.parse(source || "[]"); return Array.isArray(values) ? values.filter((item): item is string => typeof item === "string" && Boolean(item.trim())).slice(0, 30) : []; } catch { return []; } }
function parseIds(source: string) { try { const values = JSON.parse(source); return Array.isArray(values) ? values.map(Number).filter(Number.isInteger).slice(0, 5) : []; } catch { return []; } }
function safeImage(event: SyntheticEvent<HTMLImageElement>) { const image = event.currentTarget; if (image.dataset.fallbackApplied === "true") { image.style.visibility = "hidden"; return; } image.dataset.fallbackApplied = "true"; image.src = fallback; }

export default function PropertyDetail() {
  const [, params] = useRoute("/vivienda/:slug");
  const [locale, setLocale] = useState<Locale>(() => {
    if (typeof window === "undefined") return "es";
    const saved = window.localStorage.getItem("vivienda-nova:locale");
    return (locales.some((item) => item.code === saved) ? saved : "es") as Locale;
  });
  const [galleryIndex, setGalleryIndex] = useState(0);
  const [mapVisible, setMapVisible] = useState(false);
  const [expanded, setExpanded] = useState(false);
  const [formState, setFormState] = useState<"idle" | "sending" | "sent" | "error">("idle");
  const settingsQuery = trpc.settings.public.useQuery();
  const sectionsQuery = trpc.propertySections.list.useQuery({ placement: "property" });
  const isAdminPreview = typeof window !== "undefined" && new URLSearchParams(window.location.search).get("preview") === "admin";
  const adminPropertiesQuery = trpc.admin.properties.useQuery(undefined, { enabled: isAdminPreview });
  const settings = (settingsQuery.data ?? { enabledLocales: "es,en,nl,de,sv,no,fr,ro,ru,zh-CN,de-CH,fr-CH,it-CH", reservationButtonText: "Solicitar reserva", reservationButtonBackground: "#8bbf9f", reservationButtonColor: "#112f3f", relatedPropertiesCount: 5, cardStyle: "flat" }) as Settings;
  const enabledLocales = settings.enabledLocales.split(",").filter((code): code is Locale => locales.some((item) => item.code === code));
  const propertiesQuery = trpc.properties.list.useQuery({ locale });
  const allProperties = ((isAdminPreview ? adminPropertiesQuery.data : propertiesQuery.data) ?? []) as Property[];
  const property = useMemo(() => allProperties.find((item) => item.slug === params?.slug), [allProperties, params?.slug]);
  const reservation = trpc.properties.createReservationLead.useMutation();
  const copy = labels[locale] || labels.es;
  const localizedUi: { readMore: string; showLess: string; placeholder: string; sending: string; preview: string; draft: string } = ({
    es: { readMore: "Leer descripción completa", showLess: "Mostrar resumen", placeholder: "Indica cualquier detalle que necesites.", sending: "Enviando…", preview: "Vista previa", draft: "Borrador privado" },
    en: { readMore: "Read full description", showLess: "Show summary", placeholder: "Tell us anything else you need.", sending: "Sending…", preview: "Preview", draft: "Private draft" },
    de: { readMore: "Vollständige Beschreibung lesen", showLess: "Zusammenfassung anzeigen", placeholder: "Weitere Angaben oder Wünsche.", sending: "Wird gesendet…", preview: "Vorschau", draft: "Privater Entwurf" },
    fr: { readMore: "Lire la description complète", showLess: "Afficher le résumé", placeholder: "Indiquez tout autre détail.", sending: "Envoi…", preview: "Aperçu", draft: "Brouillon privé" },
  } as Record<string, { readMore: string; showLess: string; placeholder: string; sending: string; preview: string; draft: string }>)[locale] || { readMore: "Read full description", showLess: "Show summary", placeholder: "Tell us anything else you need.", sending: "Sending…", preview: "Preview", draft: "Private draft" };
  const gallery = parseGallery(property?.galleryUrls, property?.imageUrl);
  const features = parseFeatures(property?.features);
  const reserveText = settings.reservationButtonText?.trim() || copy.reserve;
  const reserveStyle = { background: settings.reservationButtonBackground || "#8bbf9f", color: settings.reservationButtonColor || "#112f3f" };
  const location = property?.address || [property?.zone, property?.city, property?.country || "España"].filter(Boolean).join(", ");
  const descriptionMode = property?.descriptionMode === "full" ? "full" : property?.descriptionMode === "compact" ? "compact" : (property?.description.length || 0) > 720 ? "compact" : "full";
  const scrollInside = property?.descriptionMode === "scroll";
  const shouldClamp = descriptionMode === "compact" && !expanded;
  const related = useMemo(() => { if (!property) return []; const maximum = Math.min(5, Math.max(1, settings.relatedPropertiesCount || 5)); return allProperties.filter((item) => item.id !== property.id).map((item) => ({ item, score: (item.type.toLocaleLowerCase() === property.type.toLocaleLowerCase() ? 100 : 0) + (item.city === property.city ? 30 : 0) + (item.zone === property.zone ? 18 : 0) + (item.featured ? 8 : 0) - Math.min(10, Math.abs(item.priceValue - property.priceValue) / Math.max(1, property.priceValue) * 10) })).sort((first, second) => second.score - first.score || second.item.priceValue - first.item.priceValue).slice(0, maximum).map(({ item }) => item); }, [allProperties, property, settings.relatedPropertiesCount]);
  const sections = (sectionsQuery.data ?? []) as Section[];

  useEffect(() => {
    const navigation = performance.getEntriesByType("navigation")[0] as PerformanceNavigationTiming | undefined;
    if (navigation?.type === "reload") window.location.replace("/");
  }, []);
  useEffect(() => {
    if (!window.localStorage.getItem("vivienda-nova:locale") && enabledLocales.length) setLocale(detectLocale(enabledLocales));
  }, [settings.enabledLocales, enabledLocales.length]);
  useEffect(() => { window.localStorage.setItem("vivienda-nova:locale", locale); }, [locale]);
  useEffect(() => { document.documentElement.lang = locale; }, [locale]);
  useEffect(() => { setGalleryIndex(0); setMapVisible(false); setExpanded(false); }, [property?.id]);
  useEffect(() => { if (!property) return; document.title = `${property.title} | Vivienda Nova`; const description = document.querySelector('meta[name="description"]') || document.head.appendChild(document.createElement("meta")); description.setAttribute("name", "description"); description.setAttribute("content", property.description.slice(0, 155)); const canonical = document.querySelector('link[rel="canonical"]') || document.head.appendChild(document.createElement("link")); canonical.setAttribute("rel", "canonical"); canonical.setAttribute("href", `${window.location.origin}/vivienda/${property.slug}`); }, [property]);

  const showMap = () => { setMapVisible(true); window.setTimeout(() => document.getElementById("mapa-propiedad")?.scrollIntoView({ behavior: "smooth", block: "center" }), 0); };
  const submitReservation = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); if (!property) return; const form = new FormData(event.currentTarget); setFormState("sending"); try { await reservation.mutateAsync({ propertyId: property.id, name: String(form.get("name") || ""), email: String(form.get("email") || ""), phone: String(form.get("phone") || "") || null, preferredDate: String(form.get("preferredDate") || "") || null, guests: Number(form.get("guests") || 1), message: String(form.get("message") || ""), privacyAccepted: form.get("privacyAccepted") === "on", reservationConsent: form.get("reservationConsent") === "on" }); event.currentTarget.reset(); setFormState("sent"); } catch { setFormState("error"); } };

  if (propertiesQuery.isLoading || (isAdminPreview && adminPropertiesQuery.isLoading)) return <main className="property-page property-page--loading"><p>Cargando vivienda…</p></main>;
  if (!property) return <main className="property-page property-page--loading"><p>Esta vivienda no está disponible.</p><Link href="/" className="button button--ink"><ArrowLeft size={16} /> {copy.back}</Link></main>;
  return <main className="property-page">
    <header className="property-page__topbar"><Link href="/" className="property-page__back"><ArrowLeft size={16} /> {copy.back}</Link><div className="property-page__locales">{enabledLocales.map((item) => <button type="button" key={item} onClick={() => { setLocale(item); window.localStorage.setItem("vivienda-nova:locale", item); }} className={locale === item ? "is-active" : ""}>{locales.find((entry) => entry.code === item)?.label}</button>)}</div></header>
    <section className="property-page__hero"><div className="property-page__gallery"><img src={gallery[galleryIndex] || property.imageUrl} alt={property.title} fetchPriority="high" onError={safeImage} />{gallery.length > 1 ? <div className="property-page__thumbnails">{gallery.slice(0, 18).map((image, index) => <button type="button" key={`${image}-${index}`} className={index === galleryIndex ? "is-active" : ""} onClick={() => setGalleryIndex(index)}><img src={image} alt={`${property.title} ${index + 1}`} loading="lazy" onError={safeImage} /></button>)}</div> : null}</div><div className="property-page__summary"><p className="eyebrow eyebrow--dark">{property.tag}</p><p className="property-page__reference">REF. {property.referenceCode || property.id}</p><h1>{property.title}</h1><p className="property-page__price">{property.price}</p><button type="button" className="property-page__location" onClick={showMap}><MapPin size={17} /> {location}</button><div className="property-page__specs"><span><House size={17} /> {property.type}</span><span><BedDouble size={17} /> {property.bedrooms} {copy.bedrooms}</span><span><Bath size={17} /> {property.bathrooms} {copy.bathrooms}</span><span><Ruler size={17} /> {property.surface} m²</span></div>{isAdminPreview ? <p className="property-page__preview-note">Vista previa privada: esta ficha no acepta reservas hasta que se publique.</p> : <a href="#reserva" className="property-page__reserve" style={reserveStyle}><CalendarDays size={18} /> {reserveText}</a>}</div></section>
    <section className="property-page__content"><article><p className="eyebrow eyebrow--dark">{copy.description}</p><h2>{copy.about}</h2><div className={`property-page__description-wrap ${shouldClamp ? "is-clamped" : ""} ${scrollInside ? "is-scrollable" : ""}`} style={shouldClamp || scrollInside ? { maxHeight: Math.max(120, property.descriptionHeight || 260) } : undefined}><p className="property-page__description">{property.description}</p></div>{descriptionMode === "compact" ? <button className="property-page__read-more" type="button" onClick={() => setExpanded(!expanded)}>{expanded ? `− ${localizedUi.showLess}` : `+ ${localizedUi.readMore}`}</button> : null}{features.length ? <section className="property-page__features"><h3>{copy.features}</h3><div>{features.map((feature) => <span key={feature}><Check size={14} /> {feature}</span>)}</div></section> : null}</article><aside className="property-page__contact"><p className="eyebrow eyebrow--dark">{isAdminPreview ? localizedUi.preview : copy.availability}</p><h2>{isAdminPreview ? localizedUi.draft : copy.request}</h2><p>{isAdminPreview ? "Comprueba el diseño, fotos, texto, características y mapa. Publica desde el administrador cuando esté lista." : copy.reservationText}</p>{!isAdminPreview ? <a href="#reserva" style={reserveStyle} className="property-page__reserve property-page__reserve--small"><CalendarDays size={17} /> {reserveText}</a> : null}</aside></section>
    <section id="mapa-propiedad" className="property-map-section"><div><p className="eyebrow eyebrow--dark"><MapPin size={15} /> {copy.location}</p><h2>{copy.map}</h2><p>{location}</p><button type="button" className="property-map-section__button" onClick={() => setMapVisible(!mapVisible)}><MapPin size={17} /> {mapVisible ? copy.hideMap : copy.showMap} <ChevronDown size={16} className={mapVisible ? "is-open" : ""} /></button></div><div className="property-map-section__canvas">{mapVisible ? <iframe title={`${copy.map}: ${property.title}`} loading="lazy" referrerPolicy="no-referrer-when-downgrade" src={`https://www.google.com/maps?q=${encodeURIComponent(property.latitude && property.longitude ? `${property.latitude},${property.longitude}` : location)}&output=embed`} /> : <button type="button" onClick={() => setMapVisible(true)} className="property-map-section__placeholder"><MapPin size={27} /><strong>{copy.showMap}</strong><span>{copy.location}</span></button>}</div></section>
    {!isAdminPreview ? <section id="reserva" className="property-reservation"><div><p className="eyebrow eyebrow--dark">{copy.reserve}</p><h2>{property.title}</h2><p>{copy.reservationText}</p><span className="property-reservation__reference">REF. {property.referenceCode || property.id} · {location}</span></div><form onSubmit={submitReservation}><label>{copy.name}<input required name="name" autoComplete="name" /></label><label>{copy.email}<input required name="email" type="email" autoComplete="email" /></label><label>{copy.phone}<input required name="phone" type="tel" autoComplete="tel" /></label><label>{copy.date}<input name="preferredDate" type="date" min={new Date().toISOString().slice(0, 10)} /></label><label>{copy.guests}<select name="guests" defaultValue="1"><option value="1">1</option><option value="2">2</option><option value="3">3</option><option value="4">4</option><option value="5">5+</option></select></label><label className="property-reservation__message">{copy.message}<textarea name="message" required rows={4} placeholder={localizedUi.placeholder} /></label><label className="property-reservation__consent"><input required name="privacyAccepted" type="checkbox" /> {copy.consent}</label><label className="property-reservation__consent"><input required name="reservationConsent" type="checkbox" /> {copy.consentReservation}</label><button disabled={formState === "sending"} style={reserveStyle} className="property-page__reserve">{formState === "sending" ? localizedUi.sending : <><Send size={17} /> {copy.send}</>}</button>{formState === "sent" ? <p className="form-success"><Check size={16} /> {copy.sent}</p> : null}{formState === "error" ? <p className="form-error">{copy.error}</p> : null}</form></section> : null}
    <PropertyCarousel title={copy.related} subtitle={copy.autoRelated} properties={related} cardStyle={settings.cardStyle || "shadow"} compact />
    {sections.map((section) => <PropertyCarousel key={section.id} title={section.title} subtitle={section.subtitle} properties={parseIds(section.propertyIds).map((id) => allProperties.find((item) => item.id === id)).filter((item): item is Property => Boolean(item))} cardStyle={section.cardStyle} background={section.background} compact />)}
  </main>;
}
