import { ChangeEvent, useEffect, useState } from "react";
import { useAuth } from "@/_core/hooks/useAuth";
import { trpc } from "@/lib/trpc";
import { ImagePlus, Loader2, Plus, Save, Trash2, Upload, Video } from "lucide-react";
import { toast } from "sonner";
import { parseEditorialCards, type EditorialCard } from "./EditorialCards";
import "./EditorialCardsManager.css";

const newCard = (type: EditorialCard["type"] = "image"): EditorialCard => ({ id: crypto.randomUUID(), type, title: "", description: "", url: "", background: "#112f3f", textColor: "#fffdf8", width: 6, height: 360, active: true });
export default function EditorialCardsManager() {
  const { user } = useAuth(); const utils = trpc.useUtils(); const settingsQuery = trpc.admin.settings.useQuery(undefined, { enabled:user?.role === "admin" }); const save = trpc.admin.updateSettings.useMutation(); const uploadImage = trpc.admin.uploadImage.useMutation(); const uploadVideo = trpc.admin.uploadHeroVideo.useMutation();
  const current = settingsQuery.data; const [cards, setCards] = useState<EditorialCard[]>([]); const [loaded, setLoaded] = useState(false);
  useEffect(() => { if (current && !loaded) { setCards(parseEditorialCards(current.editorialCards).map((card) => ({ ...card, active:true }))); setLoaded(true); } }, [current, loaded]);
  if (user?.role !== "admin") return null;
  const persist = async (next: EditorialCard[]) => { if (!current) return; await save.mutateAsync({ bannerText:current.bannerText, bannerBackground:current.bannerBackground, bannerColor:current.bannerColor, bannerHeight:current.bannerHeight, bannerRotationSeconds:current.bannerRotationSeconds, cardStyle:current.cardStyle, enabledLocales:current.enabledLocales, heroVideos:current.heroVideos ?? undefined, heroImageUrl:current.heroImageUrl ?? undefined, contactPhone:current.contactPhone ?? undefined, midPageCta:current.midPageCta ?? undefined, editorialCards:JSON.stringify(next) }); setCards(next); await Promise.all([utils.admin.settings.invalidate(), utils.settings.public.invalidate()]); toast.success("Tarjetas editoriales guardadas"); };
  const change = (id:string, field:keyof EditorialCard, value:unknown) => setCards((items) => items.map((card) => card.id === id ? { ...card, [field]:value } : card));
  const upload = (event:ChangeEvent<HTMLInputElement>, id:string, type:EditorialCard["type"]) => { const file=event.target.files?.[0]; event.target.value=""; if(!file)return; const valid=type === "image" ? ["image/jpeg","image/png","image/webp"].includes(file.type) && file.size<=20_000_000 : ["video/mp4","video/webm"].includes(file.type) && file.size<=45_000_000; if(!valid){toast.error(type === "image" ? "JPG, PNG, WebP o AVIF · máximo 20 MB. Se optimiza automáticamente antes de guardar." : "MP4 o WebM · máximo 45 MB.");return;} const reader=new FileReader(); reader.onload=()=>{ const mutation=type === "image" ? uploadImage : uploadVideo; mutation.mutate({ filename:file.name, mimeType:file.type as never, base64:String(reader.result) } as never, { onSuccess:(result)=>{change(id,"url",result.url);toast.success("Archivo cargado; guarda la tarjeta para publicarlo.");},onError:()=>toast.error("No se pudo cargar el archivo.") }); }; reader.readAsDataURL(file); };
  return <section className="editorial-cards-manager"><div className="editorial-cards-manager__top"><div><p className="admin-kicker"><span /> Contenido configurable</p><h2>Tarjetas <em>editoriales.</em></h2><p>Añade bloques con foto o vídeo y ajusta tamaño, altura y colores sin tocar el diseño general.</p></div><div className="editorial-cards-manager__actions"><button type="button" onClick={()=>setCards((items)=>[...items,newCard("image")])}><Plus size={15}/> Foto</button><button type="button" onClick={()=>setCards((items)=>[...items,newCard("video")])}><Video size={15}/> Vídeo</button><button type="button" className="is-save" disabled={save.isPending} onClick={()=>persist(cards)}>{save.isPending?<Loader2 className="spin" size={15}/>:<Save size={15}/>} Guardar</button></div></div>{settingsQuery.isLoading ? <p className="editorial-cards-manager__empty"><Loader2 className="spin"/> Cargando…</p> : <div className="editorial-cards-manager__list">{cards.map((card,index)=><div className="editorial-card-editor" key={card.id}><div className="editorial-card-editor__bar"><strong>{index+1}. {card.type === "image" ? "Foto" : "Vídeo"}</strong><button type="button" onClick={()=>setCards((items)=>items.filter((item)=>item.id!==card.id))} aria-label="Eliminar tarjeta"><Trash2 size={15}/></button></div><div className="editorial-card-editor__grid"><label>Título<input value={card.title} onChange={(e)=>change(card.id,"title",e.target.value)} /></label><label>Descripción<textarea value={card.description} onChange={(e)=>change(card.id,"description",e.target.value)} /></label><label>Ancho (1–12)<input type="number" min="1" max="12" value={card.width} onChange={(e)=>change(card.id,"width",Number(e.target.value))}/></label><label>Alto (px)<input type="number" min="180" max="900" value={card.height} onChange={(e)=>change(card.id,"height",Number(e.target.value))}/></label><label>Fondo<input type="color" value={card.background} onChange={(e)=>change(card.id,"background",e.target.value)}/></label><label>Texto<input type="color" value={card.textColor} onChange={(e)=>change(card.id,"textColor",e.target.value)}/></label><label className="editorial-card-editor__file"><Upload size={14}/> {card.url ? "Cambiar archivo" : "Cargar archivo"}<input type="file" accept={card.type === "image" ? "image/jpeg,image/png,image/webp,image/avif" : "video/mp4,video/webm"} onChange={(e)=>upload(e,card.id,card.type)}/></label></div><div className="editorial-card-editor__preview" style={{background:card.background,color:card.textColor,minHeight:Math.min(card.height,240)}}>{card.url ? (card.type === "image" ? <img src={card.url} alt="Vista previa"/> : <video src={card.url} muted playsInline controls preload="metadata"/>) : <ImagePlus size={22}/>}<span>{card.title || "Vista previa"}</span></div></div>)}{!cards.length&&<p className="editorial-cards-manager__empty">No hay tarjetas. Añade una foto o un vídeo para crear el bloque editorial.</p>}</div>}</section>;
}
